FROM scratch

LABEL org.opencontainers.image.title="Fabric-SDK" \
      org.opencontainers.image.description="BGP-style routing dashboard for Fabric-SDK" \
      org.opencontainers.image.vendor="git-fabric" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.source="https://github.com/git-fabric/fabric-forge" \
      com.docker.desktop.extension.api.version="0.3.4" \
      com.docker.desktop.extension.icon="fabric-sdk.svg"

COPY metadata.json .
COPY fabric-sdk.svg .
COPY ui ui
