apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    fabric-sdk/component: cache
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
