apiVersion: v1
kind: Service
metadata:
  name: fabric-k8s
  labels:
    app: fabric-k8s
    fabric-sdk/component: fabric
    fabric-sdk/as: "65002"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
  selector:
    app: fabric-k8s
