apiVersion: v1
kind: Service
metadata:
  name: fabric-gateway
  labels:
    app: fabric-gateway
    fabric-sdk/component: gateway
    fabric-sdk/layer: L3
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
  selector:
    app: fabric-gateway
